apiVersion: 3
dataDisplay:
  excludedFeatures: []
  noneValues:
  - none
  - unknown
  - null
  - NA
docs:
  docPage: about
  featureBase: '{docBase}/transcription.md'
  featurePage: transcription
interfaceDefaults: {}
provenanceSpec:
  corpus: '{org} - {repo}'
  doi: 10.5281/zenodo.notyet
  moduleSpecs: []
  version: '«version»'
  webBase: 'https://public.{org}.org/{repo}'
  webHint: Show this on the website
  webLang: en
  webUrl: '{webBase}/<1>/<2>/<3>&version={version}'
  webUrlLex: '{webBase}/word?version={version}&id=<lid>'
typeDisplay: {}
writing: ''
